---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kube.tessa.io.kube.state.machine
  resources:
  - statemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube.tessa.io.kube.state.machine
  resources:
  - statemachines/finalizers
  verbs:
  - update
- apiGroups:
  - kube.tessa.io.kube.state.machine
  resources:
  - statemachines/status
  verbs:
  - get
  - patch
  - update
