# permissions for end users to edit statemachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statemachine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-state-machine
    app.kubernetes.io/part-of: kube-state-machine
    app.kubernetes.io/managed-by: kustomize
  name: statemachine-editor-role
rules:
- apiGroups:
  - kube.tessa.io.kube.state.machine
  resources:
  - statemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube.tessa.io.kube.state.machine
  resources:
  - statemachines/status
  verbs:
  - get
