apiVersion: kube.tessa.io.kube.state.machine/v1
kind: StateMachine
metadata:
  labels:
    app.kubernetes.io/name: statemachine
    app.kubernetes.io/instance: statemachine-sample
    app.kubernetes.io/part-of: kube-state-machine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-state-machine
  name: statemachine-sample
spec:
  states:
    - name: first-job
      type: Task
      task:
        containers:
          - name: pi-job
            image: perl:5.34.0
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        restartPolicy: Never
      end: true
